version: '3'

services:
  obs-node-api:
    container_name: obs-node-api
    image: node:18
    restart: on-failure
    working_dir: /app
    ports:
      - "5454:5454"
    volumes:
      - ./:/app
    platform: linux/arm64/v8
    command:
      - sh
      - -c
      - |
        apt-get update 
        apt-get install wget
        apt-get install -y build-essential chrpath libssl-dev libxft-dev
        wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
        tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
        mv phantomjs-2.1.1-linux-x86_64 /usr/local/share/
        ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
        /usr/local/bin/phantomjs --version
        npm start



    

