version: '3'
services:


  nodejs-obs-app:
    image: node:18
    container_name: suat-obs
    working_dir: /app
    restart: unless-stopped
    ports:
      - "5454:5454"
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
